name: Publish

on:
  push:
    branches:
      - "main-slsa-test"
    tags:
      - "*"

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    name: Go Version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt-get install -y gnutls-bin softhsm2

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Fake build
        run: |
          mkdir dist
          cd dist
          echo -en "12345" > output1
          echo -en "abcde" > output2

      - name: "Generate hashes"
        id: hash
        run: |
          cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT

      - name: "Upload dists"
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: "dist"
          path: "dist/"
          if-no-files-found: error

      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/

